### ISSUE TITLE
ql as context broker datasource

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#102]
context broker is supporting "registration" as way to register external data sources for entities. this means that when queried, the context broker will answer by query the external data source.
ideally QL could act as a data source returning the last value of a given entity. this could be particularly interesting in combination with #101

**Comment by pooja1pathak** [comment]
Hi @chicco785 I would like to contribute on this issue. Please assign it to me.

**Comment by c0c0n3** [comment]
@pooja1pathak 

> Please assign it to me.

done, thank you so much!

**Comment by pooja1pathak** [comment]
@chicco785 @c0c0n3 I have checked the APIs. As we already have query parameter ```lastN``` to get the latest value except for ```/v2/entities```, please find below suggestions for resolution of this issue:
1. We can include attribute name and last value in the response of ```/v2/entities``` and return response as returned in case of [orion](https://fiware-orion.readthedocs.io/en/master/user/walkthrough_apiv2/index.html#getting-all-entities-and-filtering)
OR
2. Create a new API ```/v2/<entityID>``` returning the last value of a given entity as returned in case of [orion](https://fiware-orion.readthedocs.io/en/master/user/walkthrough_apiv2/index.html#query-entity).

Kindly review my suggestion and let me know in which direction I can proceed.

**Comment by pooja1pathak** [comment]
As per my understanding we should opt for option 2 i.e., Create a new API ```/v2/<entityID>``` returning the last value of a given entity.

I am working on that part. Please let me know if you have any other suggestion or concern.

**Comment by pooja1pathak** [comment]
Closing this issue as #502  is merged.
