### ISSUE TITLE
Handle aggregation on invalid columns

### ISSUE THREAD

**Issue by taliaga** [orchestracities/ngsi-timeseries-api#106]
`sum` and a `avg` should not be allowed on `attr_names` (attributes) of non-numeric types.

Note `min`, `max` and `count` still work on things like `bool` or `string`.

**Comment by pooja1pathak** [comment]
@chicco785 @c0c0n3 I would like to contribute on this issue. Please assign it to me.

**Comment by pooja1pathak** [comment]
Hi @chicco785 @c0c0n3 I have analyzed this issue. As per my analysis this issue does not exists in present code.

I have tested with ```attributes``` of non-numeric types i.e. ```Boolean``` and ```Text```. For ```sum``` and ```avg``` the output of the query is ```404NOT FOUND``` with the body:
```
{
    "description": "No records were found for such query.",
    "error": "Not Found"
}
```
While for ```min```, ```max``` and ```count``` , query returns the correct response.

Please confirm my understanding and let me know if we are expecting this behavior from QL or need anything else.

**Comment by c0c0n3** [comment]
Hi @pooja1pathak thanks for looking into this, that's great! Can you add your tests to the reporter? Just to make out test suite more robust :-)

Regarding the returned code and message, it should be better in my opinion. If an operation makes no sense for a given type we should say so explicitly, rather than making the client believe there's no records. Thoughts?

**Comment by pooja1pathak** [comment]
Hi @c0c0n3 , 
> Regarding the returned code and message, it should be better in my opinion. If an operation makes no sense for a given type we should say so explicitly, rather than making the client believe there's no records. Thoughts?

in sql_translator.py https://github.com/orchestracities/ngsi-timeseries-api/blob/4c9bdc42a06f9d6a45b9dc107dd95428ee2c284f/src/translators/sql_translator.py#L1112 , empty entity is returned in case any exception occur in sql query. So, in query_XXXX.py when no entity is received it returns ```404 NOT FOUND``` as response. 
For example in case of Boolean if ```aggrMethod=avg``` is used then sql exception occurs as: 
```
crate.client.exceptions.ProgrammingError: SQLActionException[SQLParseException: Cannot cast boolean to type [double precision, real, timestamp with time zone, integer, smallint, char]] 
``` 
which leads to ```404 NOT FOUND``` response.

As per your opinion we can catch such type of exception at https://github.com/orchestracities/ngsi-timeseries-api/blob/4c9bdc42a06f9d6a45b9dc107dd95428ee2c284f/src/translators/sql_translator.py#L1106 and return more informative response to the user like ```aggrMethod cannot be applied```.

Please suggest if I can work in this direction and raise PR for the same.

**Comment by pooja1pathak** [comment]
Hi @c0c0n3 @chicco785 I have raise PR #499 as a fix for this issue by adding test cases. Some already written test cases are failing in my local debug environment. Can you raise a separate issue for the same if test cases have some issue which we can fix? 
I will start working on the issue once it is raised :-)

**Comment by chicco785** [comment]
@c0c0n3 not sure after the last pr by @pooja1pathak this can be closed

**Comment by pooja1pathak** [comment]
As per https://github.com/orchestracities/ngsi-timeseries-api/issues/106#issuecomment-876646841 , we only need to add tests. Closing this issue as PR is merged.
