### ISSUE TITLE
extend travis tests to be able to validate behavior of ql with different version of related components

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#134]
e.g. orion version x / mongo version y / crate version z

**Comment by c0c0n3** [comment]
reopening this just to double-check what happened to the test matrix...
#459 moved our build infrastructure to CircleCI, but what happened to the test matrix we had in Travis?
@chicco785 is this still relevant, pls help! :-)

**Comment by chicco785** [comment]
well, in travis it was there :) we have to see what to do for circle ci, but it would be another issue i suppose

**Comment by c0c0n3** [comment]
cool :-) opened #467 about it.
