### ISSUE TITLE
Support retention policy

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#15]
how long to keep data of a given entity and at which resolution?
e.g. after 1 year, I may be happy to keep instead of all data, only interpolation of data for 1h or so.

**Comment by taliaga** [comment]
Brainstorming, this could be configured:
- In the configuration file mentioned in #10
- In the NGSI notification (but NGSI currently does not support this)
- Configurable via protected API?

**Comment by chicco785** [comment]
ngsi now supports 'dateExpires': http://fiware.github.io/specifications/ngsiv2 (so it's in the entity not in the subscription)
I propose then to have two ways:
1. leverage this attribute (if it exists)
1. have a default set-up via config file (that should be also the case for #10 )
1. configure it via API entity by entity (or entity type) of course using the tenant split

**Comment by c0c0n3** [comment]
as far as I can tell, this has never been implemented? but should this functionality be in QL or rather a DB admin task?

**Comment by chicco785** [comment]
i think, considering that timescale supports that, this is a more db specific thing
