### ISSUE TITLE
Support a default way in the entity data model to track entity instances ownership.

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#18]
Scenario:
1. keep track of who injected a certain entity instance. (this should be a "compulsory" attribute in the data model. It could be the dataProvider field defined in the [GSMA-Commons](https://raw.githubusercontent.com/Fiware/dataModels/master/common-schema.json).
```"GSMA-Commons": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/EntityIdentifierType"
        },
        "dateCreated": {
          "type": "string",
          "format": "date-time"
        },
        "dateModified": {
          "type": "string",
          "format": "date-time"
        },
        "source": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "alternateName": {
           "type": "string" 
        },
        "description": {
           "type": "string" 
        },
        "dataProvider": {
          "type": "string"
        }
      }
    },
```
1. if a model is inject that does not have the field, raise a warning.
1. Based on an external authz mechanism allow a user to access a given entity instance based on the policy defined by the data provider. This should work both via the NGSI API and the CrateDB API (see #17).

**Comment by Necravisaketi** [comment]
Hi, @c0c0n3 @chicco785 do we need to add the field on context provider or something else? Do you confirm where we need to add this feature.

**Comment by c0c0n3** [comment]
Hi @Necravisaketi, this is an old issue, I'm not entirely sure what to do about. @chicco785 and @Cerfoglg are developing a fully-fledged external authz solution for FIWARE:

- https://github.com/orchestracities/anubis

So we should probably review this issue in light of this new development? @chicco785?

**Comment by chicco785** [comment]
i think owernship is not necessarily related to anubis. for sure, anyhow, it makes more sense to tackle this w.r.t. orion than quantumleap, since we are just "copying" values from it.
