### ISSUE TITLE
Release 0.7 reloaded!

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/ngsi-timeseries-api#219]
### The problem
Release 0.7 (#216) brought in a breaking API change. While the query semantics remained exactly the same, the result representation format changed slightly---see #214, #213. Even though technically this isn't a "semantic change", we should still consider bumping up the major version number to 1 since that's what semantic versioning requires and we're supposed to stick to it--- @jason-fox thanks for pointing that out :-)

### Proposed solution
* Release 1.0 but mention explicitly this isn't a fully-fledged product yet.
* Update the Quantum Leap tutorial to reflect the new query result format.

### Alternatives
* Make 0.7 an "internal" release as we discussed already?
* Ideas anyone?!

### Additional context
The issue of semantic versioning was brought up during the Fiware meeting of 24 Jun 2019.

**Comment by c0c0n3** [comment]
@taliaga @chicco785 @jason-fox 
One thing to consider though is that our API is somewhat still in the flux---think state-related queries! So as we experiment and explore new avenues there will be lots of breaking API changes. If we stick to semantic versioning and bump up the major version number each time, we might wind up on version 7 or 11 or whatever in a short period of time---think months rather than years. In my experience people tend to relate major version numbers to product maturity, so releasing e.g. Quantum Leap v3.0 in the next couple of months might be misleading in terms of product maturity expectations?

@jason-fox would the following be acceptable to the Fiware foundation: keep on using our informal versioning scheme until we stabilise the API, at which point we release version 1.0 and from that point on we switch to semantic versioning.

**Comment by c0c0n3** [comment]
@jason-fox a variation on the theme would be to use semantic versioning at the API level for the interim.
In fact, we deliver Quantum Leap as a REST API, not as a Python library. So we could keep our own informal versioning scheme for the Python code and bump up the API major version number independently as/when needed. In detail:

1. The API spec we released with 0.7 gets a 1.0.0 version number on SwaggerHub.
2. We keep release 0.7 as is but we mention the API version corresponding to this release is 1.0.
3. If the next 0.x Quantum Leap (code release) is backward-compatible at the API level with 0.7, the API major version numbers stays 1 otherwise it becomes 2.0.
4. From now on, release notes will mention what is the API version number associated with each release.

I initially voted against this since I find it somewhat confusing and it's definitely more book keeping, but perhaps it could be a happy medium at this stage. Thoughts?

**Comment by chicco785** [comment]
@c0c0n3 should we keep it?

**Comment by c0c0n3** [comment]
@chicco785 there was no follow up on this. My take is that we can use a bit more relaxed versioning scheme until we make it to 1.0. Past that point we should stick to "strict" semantic versioning as required by FIWARE.
