### ISSUE TITLE
FIWARE Generic Enabler Compliance

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/ngsi-timeseries-api#277]
**Is your feature request related to a problem? Please describe.**
This issue is a follow-up to the Nov 2019 Fiware TSC conf call where we promised we'd look into what still needs doing to have QuantumLeap meet the [Fiware GE requirements][fw-ge-req].

**Describe the solution you'd like**
Review the [Fiware GE requirements][fw-ge-req], collect them in a checklist and for each item say if  QL meets the requirement already or if not detail what needs doing, cross linking the item with the GitHub issue that will implement the requirement. Example:

- [x] **Contributions to master MUST come in the form of a Pull Request**. We've been doing this since the beginning of the project.
- [ ] **Elevator pitch, the "What is?" and "Why use?"**. Need some work, see #xxx (xxx = GitHub issue number)

Keep the checklist here on GitHub and update it as features get implemented, taking care of referencing relevant PRs, e.g.

- [x] **Elevator pitch, the "What is?" and "Why use?"**. Reworded docs, see #xxx (xxx = GitHub PR number)
 

[fw-ge-req]: https://fiware-requirements.readthedocs.io/en/latest/
    "Fiware Generic Enabler Requirements"

**Comment by c0c0n3** [comment]
@chicco785 if you could please tag any core chapter member who may be interested in following progress on this, e.g. @fgalan?

**Comment by chicco785** [comment]
@c0c0n3 most probably we can close this

**Comment by c0c0n3** [comment]
yep, we got our GE badge, #457.
