### ISSUE TITLE
2020 Roadmap Update

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/ngsi-timeseries-api#284]
**Is your feature request related to a problem? Please describe.**
This issue is a follow-up to the Jan 2020 Fiware TSC where we were kindly reminded to update our roadmap for 2020---thanks @jason-fox.

**Describe the solution you'd like**
As discussed during the meeting, support for NGSI-LD should be one of our top priorities for 2020. This could happen through multiple releases in 2020, each providing incremental support---e.g. entity storage, basic temporal queries, entity/relationship storage, relational temporal queries. Ideally, temporal queries should be implemented as required by the NGSI-LD temporal queries spec, i.e. supporting this interface would be first prize.

Other items that should probably be high in the priority list are full support for Timescale, handling of large datasets, etc. as discussed last year.

**Describe alternatives you've considered**
N/A

**Additional context**
See TSC minutes of 27 Jan 2020 and #277.

**Comment by chicco785** [comment]
@c0c0n3 we set priorities based on resources and customer requirements, so a request being made in the TSC, does not qualify it as "priority"

**Comment by c0c0n3** [comment]
@chicco785 good point. On the other hand I reckon if we want to be part of the FiWare foundation we should at least try making an effort to align our roadmap to the foundation's vision for the future? At this point though it isn't clear, at least to me, how to reconcile possibly conflicting requirements/priorities...
