### ISSUE TITLE
Aggregates of incompatible attributes

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/ngsi-timeseries-api#296]
### Is your feature request related to a problem? Please describe.
PR #294 brought in support for querying attributes across entity types---yay, thanks @daminichopra!
But we're sitting with a dilemma: how should aggregate operations work over attributes of different types? See for example test case (4) [from this comment](https://github.com/smartsdk/ngsi-timeseries-api/pull/294#issuecomment-596588209). To me, this should be treated as a client error, i.e. we should assume if a client hits `/v2/attrs` requesting an aggregate then it knows the aggregate op actually makes sense for all attrs involved in the query.

### Describe the solution you'd like
Test what happens when hitting `/v2/attrs` with an aggregate involving attributes of incompatible types---e.g. [test scenario (4)](https://github.com/smartsdk/ngsi-timeseries-api/pull/294#issuecomment-596588209) from PR #294. We should probably get a DB exception which we should catch and wrap into a `4xx` client error with an message explaining what's going on.

### Describe alternatives you've considered
* Let QL bomb out with a `5xx` and stack trace. Not nice, but a possibility.
* Remove aggregate params from `/v2/attrs` endpoint spec. Solves the problem but ditches possibly useful functionality.

### Additional context
See also `aggrScope` query param---not implemented yet.

**Comment by chicco785** [comment]
we know which attributes "instances" are numeric and which are not. simply /v2/attrs/pippo considers all the "pippo" that are numeric, the rest is discarded. if all "pippo" are non numeric, we report 404 or something like that

**Comment by c0c0n3** [comment]
Excellent, it actually didn't occur to me we could do that too. Also like [you said](https://github.com/smartsdk/ngsi-timeseries-api/pull/294#issuecomment-606572183), this may be an option too:

> from a logic point of view, as regards 4, simply there is no average. so you don't consider them.

which is basically what I'm suggesting here, modulo the `4xx`. Anyway, I've realised there are still bits and pieces of that big honking translator query that I don't grasp fully, especially when it comes to corner cases. I'll need a bit more time to dig in and figure out pros & cons about implementation effort.

**Comment by c0c0n3** [comment]
So I've done quite an extensive analysis of how querying works and put [my findings][moaq] on the [wiki][wiki]. As it turns out, at least for queries involving a single table and one attribute, Quantum Leap actually does what you're suggesting: if the attribute doesn't exist or it does exist but isn't numeric, return a `404`. If the query touches more than one table, then only return results from those tables where the attribute exists and is numeric.

Things get hairier when many tables and attributes are involved, full analysis here:

* [Success and Failure Scenarios][suc-n-fail]

But to sum up, Quantum Leap does something similar to the above by dropping results from any table where any of the requested attributes isn't numeric---e.g. if the client requested attributes `x` and `y`
and table `T` has a numeric `x` and string `y`, then no data gets collected from `T`.

However, looking at the implementation all this seems to happen more by accident than by design---we catch a SQL exception that may be raised in many other circumstances besides syntax errors and failed
type casts. Now while we could make the approach bomb proof e.g. using the "scenario" vector defined in [Success and Failure Scenarios][suc-n-fail], I'd rather go a different way for now if everyone agrees.

Here's my suggestion then, assuming we're all happy with the current approach of: returning whatever results we can collect is better than no results.

1. Write more tests to verify my analysis is correct---i.e. Quantum Leap returns whatever results it can collect. (I didn't have time to test all scenarios, there are too many.)
2. If that's the case, then close this issue.
3. Otherwise patch current implementation as needed.

Going forward, I suggest we review the approach though since I'm not convinced that returning whatever data we can get our hands on is better than e.g. telling the client there was a problem, see below issue about it.

* [Hidden data loss][hidden-loss]



[wiki]: https://github.com/smartsdk/ngsi-timeseries-api/wiki
[moaq]: https://github.com/smartsdk/ngsi-timeseries-api/wiki/The-Mother-of-all-Queries
[suc-n-fail]: https://github.com/smartsdk/ngsi-timeseries-api/wiki/Success-and-Failure-Scenarios
[hidden-loss]: https://github.com/smartsdk/ngsi-timeseries-api/wiki/Issues#hidden-data-loss

**Comment by pooja1pathak** [comment]
Hi @chicco785 @c0c0n3 I would like o contribute on this issue. Please assign it to me.

**Comment by chicco785** [comment]
hi @pooja1pathak sure, please have a look at @c0c0n3 considerations on the matter in order to proceed:
https://github.com/orchestracities/ngsi-timeseries-api/issues/296#issuecomment-613033340

**Comment by pooja1pathak** [comment]
Hi @chicco785 @c0c0n3 I have analyzed this issue and found very strange behavior of QL. Please find below points:

1. We cannot use ```aggrMethod``` without mentioning ```attrs``` in query parameter.
2. ```aggrMethod``` does not work for APIs: ```v2/entities/<entityId>```, ```v2/types/<entityType>```,```v2/attrs```

For point 1: If we are mentioning attrs in query parameter of the API then this issue ```Aggregates of incompatible attributes``` #296 will never occur. We can document this behavior somewhere in the docs and close this issue.

For point 2: We can raise a new bug mentioning the APIs for which ```aggrMethod``` does not work and handle it there.

Please confirm my understanding and provide your suggestion on implementations for point 1 and 2. :)

**Comment by c0c0n3** [comment]
Hi @pooja1pathak that;s great. Can you share your tests?

**Comment by pooja1pathak** [comment]
Hi @c0c0n3 , Please find below details:
I have created an entity in QL by notify with data:
```
{
   "subscriptionId":"5947d174793fe6f7eb5e3961",
   "data":[
      {
         "id":"Room1",
         "type":"Room",
         "temperature":{
            "type":"Number",
            "value":10
         },
         "intensity":{
            "type":"Text",
            "value":"Low"
         },
         "boolean":{
            "type":"Boolean",
            "value":1
         }
      }
   ]
}
```
Then I have executed below GET requests on QL which returned ```200 OK``` response with the data:
```
1. /v2/attrs?attrs=temperature,intensity,boolean
2. /v2/attrs?aggrMethod=min&attrs=temperature,intensity,boolean
3. /v2/attrs?aggrMethod=max&attrs=temperature,intensity,boolean
4. /v2/attrs?aggrMethod=count&attrs=temperature,intensity,boolean
```
Below are the GET request for which ```404 NOT FOUND``` is returned:
```
1.  /v2/attrs?aggrMethod=avg&attrs=temperature,intensity,boolean
2.  /v2/attrs?aggrMethod=sum&attrs=temperature,intensity,boolean
```
Please let me know if I need to add these scenarios in ```src/reporter/tests/test_NTNENA.py```

**Comment by c0c0n3** [comment]
Hi @pooja1pathak!

Sorry for the slow reply, I was away on holiday and busy w/ other projects. Also I'll be away for another two weeks, but I'll try to catch up w/ QL issues in September.

> need to add these scenarios in src/reporter/tests/test_NTNENA.py

that'd be great, I suppose you could do this as part of #498? thank you soooo much!!

**Comment by pooja1pathak** [comment]
Closing issue as PR #498 is merged.
