### ISSUE TITLE
ReadtheDocs structural issue

### ISSUE THREAD

**Issue by ilarimikkonen** [orchestracities/ngsi-timeseries-api#345]
Hi guys,

when reading https://quantumleap.readthedocs.io/en/latest/ there is a link on the left Navigation pane User->home:

![image](https://user-images.githubusercontent.com/7221736/88930652-6f1e6380-d284-11ea-85f4-6ab459e4d100.png)

when clicking that it jumps to:

![image](https://user-images.githubusercontent.com/7221736/88930716-85c4ba80-d284-11ea-9e79-0fa6dad78f3a.png)

which feels like unlocking an achievement, but somehow illogical :D

**Comment by c0c0n3** [comment]
@ilarimikkonen good catch, thanks for reporting it!

**Comment by daminichopra** [comment]
Hi @c0c0n3 @chicco785 , Please assign this issue to me.

**Comment by c0c0n3** [comment]
done thank you!!
