### ISSUE TITLE
increase coverage

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#408]
**Is your feature request related to a problem? Please describe.**

Coverage is around 70%, looking on coverall looks like reporter.py and friends are not hit!
Reason is that reporter tests are done via docker, so they are not covered.

**Describe the solution you'd like**

Have coverage to get data also from reporter and friends, probably this can work by
running pytest from the container itself and mounting a folder.

**Comment by c0c0n3** [comment]
closed by #441.
