### ISSUE TITLE
Document query pagination better

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/ngsi-timeseries-api#419]
**Is your feature request related to a problem? Please describe.**
Query pagination isn't documented thoroughly and requires some guesswork from our users to actually figure out how to use it.

**Describe the solution you'd like**
A clear explanation and examples of how to use the `limit` and `offset` parameters.

**Describe alternatives you've considered**
N/A

**Additional context**
See #417

**Comment by daminichopra** [comment]
Hi @chicco785 @c0c0n3 , Please assign this issue to me. Thank you

**Comment by c0c0n3** [comment]
@daminichopra assigned to you, thx alot!!
