### ISSUE TITLE
Remove subscription API support

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#424]
**Is your feature request related to a problem? Please describe.**
Today QL offers an API to create subscription on Orion from QL. Such API
introduce additional maintenance effort, for not real additional value.

**Describe the solution you'd like**
Deprecate and remove the API.

**Comment by pooja1pathak** [comment]
Hi @chicco785 I would like to contribute for this issue. Please assign it to me.

I want to confirm if we need to add deprecated message in API and the remove API in later release or we can remove API in this release only.

**Comment by chicco785** [comment]
hi,
deprecation message is already there:

https://github.com/orchestracities/ngsi-timeseries-api/blob/master/src/reporter/reporter.py#L236

you can proceed with the removal now, but we will merge the PR only later, is that ok?

> Hi @chicco785 I would like to contribute for this issue. Please assign it to me.
> 
> I want to confirm if we need to add deprecated message in API and the remove API in later release or we can remove API in this release only.

**Comment by pooja1pathak** [comment]
> you can proceed with the removal now, but we will merge the PR only later, is that ok?

Yes, that is perfectly fine. I'll raise the PR.

**Comment by pooja1pathak** [comment]
Closing as PR #493 is merged.
