### ISSUE TITLE
the parameters called todate and fromdate not work for me

### ISSUE THREAD

**Issue by fran748** [orchestracities/ngsi-timeseries-api#454]
Hello. I am using a server that has installed fiware. I need to receive a data series based on a certain time limits, so I need to use the parameters called todate and fromdate that are implemented in quantumleap.
I am using quntumleap 0.7.6, docker 20.10.3 , Crate DB version 4.1.4.
I can make the http request, but I don't get the data of this interval, instead the server sends me all stored datas in the entity.
Does Anyone know why this happens?
This is the request http that I do:
http://IP:Port/v2/entities/XX/attrs/Vrms3s?fromdate=2021-02-18T00:00:00.000Z& todate=2021-02-18T17:00:00.000Z

**Comment by SBlechmann** [comment]
Hey there,

I believe that 1st you have a space behind the &.
But second and more important: I believe the query parameters are case sensitive. So you might give it a try with fromDate and toDate :)

**Comment by fran748** [comment]
Thanks, thanks. You have helped me a lot, this was the problem. :)
I had not realized that, in the end it was all a misspelling.

> Hola,
> 
> Creo que primero tienes un espacio detrás del &.
> Pero segundo y más importante: creo que los parámetros de consulta distinguen entre mayúsculas y minúsculas. Así que puede intentarlo con fromDate y toDate :)

**Comment by c0c0n3** [comment]
@SBlechmann thanks so much for this.
