### ISSUE TITLE
Dead Link in Readme

### ISSUE THREAD

**Issue by DasNordlicht** [orchestracities/ngsi-timeseries-api#466]
The Lint is dead https://app.swaggerhub.com/apis/smartsdk/ngsi-tsdb

**Comment by chicco785** [comment]
thx @DasNordlicht  this probably linked to the migration to the new github repo.
while we look into that, if you need the swagger spec, you can find it in the repo:
[https://github.com/orchestracities/ngsi-timeseries-api/blob/master/specification/quantumleap.yml](https://github.com/orchestracities/ngsi-timeseries-api/blob/master/specification/quantumleap.yml)
