### ISSUE TITLE
Testing QL with different backend versions

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/ngsi-timeseries-api#467]
### Is your feature request related to a problem? Please describe.
#459 moved our build infrastructure to CircleCI, but we still have to find a way to implement test sessions where QL is configured with different versions of the same backend.

### Describe the solution you'd like
Something similar to the test matrix we had in Travis where QL gets tested with different versions of e.g. Crate.

### Describe alternatives you've considered
N/A

### Additional context
#134, #459

**Comment by chicco785** [comment]
fixed by #492
