### ISSUE TITLE
Missing entity type in /entities/v2 endpoints

### ISSUE THREAD

**Issue by tstorek** [orchestracities/ngsi-timeseries-api#478]
**Is your feature request related to a problem? Please describe.**
It would be very useful, if the /entities/... endpoints would also include the type for each entity

**Describe the solution you'd like**
Adding 'entityType' to the ResponseModels in the list of entities.

**Describe alternatives you've considered**
Unnecessary query on the /entities/ endpoint for fetching the metadata in the first place.

Related to: #476

**Comment by daminichopra** [comment]
Hi @tstorek , I was trying to check the above query and I got below response:

`curl -X 'GET'   'http://localhost:8668/v2/entities?limit=10000'   -H 'accept: text/plain'`

Response:
```
[
  {
    "id": "Room1",
    "index": [
      "2021-06-29T07:43:31.289+00:00",
      "2021-06-29T07:44:17.828+00:00"
    ],
    "type": "Room1"
  },
  {
    "id": "Room2",
    "index": [
      "2021-06-29T07:44:39.557+00:00"
    ],
    "type": "Room2"
  }
]

```
I am getting `entityType` in response. Please let me know if I am missing something.

**Comment by tstorek** [comment]
Hi,
This is correct. But if you go deeper on a dedicated entity, e. g. /entities/Room1, the info is missing, although i would expect the entity-model has to be th same in the list and the single version.

I would also suggest to return a values field in /entities containing the last value.
