### ISSUE TITLE
CLA done right

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/ngsi-timeseries-api#479]
### Describe the issue
It looks like the CLA pdf linked from the CLA template should actually sit in our repo and be customised for QL as kindly pointed out by @KazuhitoSuda-NEC:

> There is a link of individual-cla.pdf file in pull_request_template.md.
> It is outside this repository. It seems that the file is not for QuantumLeap.

Does it also need to be signed by **each** contributor or is the automated CLA signing in PRs enough? If we need a signed file for each contributor, should those files be kept in our repo too?

### Additional context
See comments about CLA on #475, especially [this one](https://github.com/orchestracities/ngsi-timeseries-api/pull/475#issuecomment-828367872).

**Comment by c0c0n3** [comment]
summoning the mighty @jason-fox to shed some light on this...

**Comment by jason-fox** [comment]
You can compare [QuantumLeap](https://github.com/orchestracities/ngsi-timeseries-api/blob/master/.github/workflows/cla.yml#L22) with [Keyrock](https://github.com/FIWARE-GEs/keyrock/blob/master/.github/workflows/cla.yml#L22) - the UPM team have created their own CLA based on the FIWARE Template - you can do the same.

> is the automated CLA signing in PRs enough? 

Yes, automated signing is enough for me. The original Git Patch was merely to ensure that a CLA signing function was in place for contributors - whilst minimizing the pain of having to maintain it.

> If we need a signed file for each contributor, should those files be kept in our repo too?

Within the [GitHub CLA Action](https://github.com/cla-assistant/github-action): 

```yml
path-to-signatures: 'signatures/version1/cla.json'
```

ensures that a list of signees is maintained in the repo.

It is my understanding that this is sufficient, but remember, I'm a developer, I don't do legal advice - I leave that to my [twin brother](https://www.linkedin.com/in/nicholas-fox-3837a78/) instead.

**Comment by KazuhitoSuda-NEC** [comment]
The pull_request_template.md file in QL repo has a link of CLA file. It's https://fiware.github.io/contribution-requirements/individual-cla.pdf. Please open it. For example, the title is `<name of FIWAER componet> Individual Contributor License Agreent`. I think that this should be updated to `FIWARE QuantumLeap Individual Contributor License Agreent`.

Please see https://github.com/ging/fiware-idm/blob/master/keyrock-individual-cla.pdf file.

**Comment by c0c0n3** [comment]
@jason-fox thanks for this, mucho appreciato.

> You can compare QuantumLeap with Keyrock

excellent, will do

> path-to-signatures: 'signatures/version1/cla.json'
> ensures that a list of signees is maintained in the repo.

we've got that in our own GH action

- https://github.com/orchestracities/ngsi-timeseries-api/blob/master/.github/workflows/cla.yml#L21

but I can't find the `cla.json` file with the signatures anywhere, so I guess we'll have to fix it.

>  my twin brother...

is a brainiac!

> I have degrees in Mathematics, Computer Science and Law and have technical experience in the areas of electronics and software

Sjoe! I wish I had 2% of his brain cells :-)

**Comment by c0c0n3** [comment]
@KazuhitoSuda-NEC

> For example, the title is <name of FIWAER componet> Individual Contributor License Agreent.
> I think that this should be updated to FIWARE QuantumLeap Individual Contributor License Agreent.

Noted, thanks a stack!!

**Comment by jason-fox** [comment]
> but I can't find the `cla.json` file with the signatures anywhere, so I guess we'll have to fix it.

`cla.json` is generated by the action.

**Comment by c0c0n3** [comment]
> cla.json is generated by the action.

d'oh! did i mention i wish i had 2% of your brother's brains :-)

**Comment by jason-fox** [comment]
> d'oh! did i mention i wish i had 2% of your brother's brains :-)

Did I mention that my twin brother speaks fluent japanese :jp: ?

自動翻訳ツールを使用しています !

**Comment by c0c0n3** [comment]
> 自動翻訳ツールを使用しています !

hahahaha, brilliant. genius seems to run in the family

**Comment by chicco785** [comment]
> but I can't find the `cla.json` file with the signatures anywhere, so I guess we'll have to fix it.

it's in the `cla-signature` branch
https://github.com/orchestracities/ngsi-timeseries-api/blob/cla-signature/signatures/version1/cla.json

**Comment by KazuhitoSuda-NEC** [comment]
@c0c0n3 
Cc: @daminichopra

Could you give us information on the current situation of this issue, please?

Thanks.

**Comment by c0c0n3** [comment]
@KazuhitoSuda-NEC @daminichopra

> current situation of this issue, please?

we'll try to get this done in the next couple of weeks. we're swamped w/ work at the moment, but we'll try to sort this out. thanks for your patience.

**Comment by KazuhitoSuda-NEC** [comment]
Thank you for your reply. I understand.

**Comment by chicco785** [comment]
@jason-fox any chance to get a word / rtf version of the entity and individual cla?

**Comment by jason-fox** [comment]
[Individual CLA proposed template.rtf.zip](https://github.com/orchestracities/ngsi-timeseries-api/files/6500341/Individual.CLA.proposed.template.rtf.zip)

**Comment by chicco785** [comment]
have a look at PR #480 and let us know
