### ISSUE TITLE
random failures on integration

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#495]
time between notifications seems to be very variable, due to that number of entries received is not always the expected one (to be debugged better)

https://github.com/orchestracities/ngsi-timeseries-api/blob/964117c42d7cf4d1c51ecfc6f9accd78976d7a2a/src/tests/common.py#L164

**Comment by pooja1pathak** [comment]
Hi @chicco785 @c0c0n3 I want to contribute on this issue. Please assign it to me.

**Comment by pooja1pathak** [comment]
@chicco785 I have reverted the fix of #508 and then ran test_integration.py in my local environment. 5 test cases are failing every time I run the test file namely:
```test_integration_basic, test_integration[t1], test_integration[t2], test_air_quality_observed[t1], test_air_quality_observed[t2]```

Each of them are failing for ```404 Not Found```. 

I am using command to run the test case as:  ```python3 -m pytest tests/test_integration.py -vv```
I have also tried to run ```run_tests.sh``` but I am unable to successfully run this file.

Can you please guide me a better way to reproduce this issue in my local environment.

**Comment by chicco785** [comment]
@pooja1pathak to actually test the issue, you need only to change this `False` into `True`:
https://github.com/orchestracities/ngsi-timeseries-api/blob/master/src/tests/test_integration.py#L53

i am not sure what's your set-up, so it may not be easy to understand why `run_tests.sh` is not working.

i suppose:
- you have docker
- you have pipenv
- you followed instructions here: https://quantumleap.readthedocs.io/en/latest/user/contributing/#development-setup

**Comment by pooja1pathak** [comment]
@chicco785 I have followed the instructions and changed False into True:
https://github.com/orchestracities/ngsi-timeseries-api/blob/master/src/tests/test_integration.py#L53. But I am unable to reproduce the issue. Only backwards_compatibility and integration test are failing for 500 in my environment, rest all the tests are passed. 

Please let me know if there is anything else I can do to reproduce this issue.

**Comment by pooja1pathak** [comment]
@chicco785 I am unable to reproduce this issue at my local environment. Please confirm if issue is reproduced at your setup.

**Comment by chicco785** [comment]
latest refactor by @c0c0n3 with the wait_for_insert, should have solved the issue. let's close and re-open if needed.
