### ISSUE TITLE
add a warning for the change of the response format from 0.9 version

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#514]
**Is your feature request related to a problem? Please describe.**
It was agreed to use `id` and `type` rather than `entityId` and `entityType` from version 0.9.
it would be good to notify users "actively"

**Describe the solution you'd like**
Let's add a warning in all query responses about the change.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/orchestracities/ngsi-timeseries-api/issues/476#issuecomment-843743475

**Comment by daminichopra** [comment]
@chicco785 , Please assign this issue to me
