### ISSUE TITLE
compute entry id for each received entity notification

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#533]
**Is your feature request related to a problem? Please describe.**
At the time being there is no unique identifier of registered timeseries entries. This  may simplify some queries, and help to support some of the ngsi-ld requirements.

From NGSI-LD spec for Properties:
* "instanceId": a URI uniquely identifying a Property instance. System generated. Optional.

For temporal representations, systems should maintain an instanceId for each Property instance. Without
such an instanceId, it is not possible to selectively modify or delete temporal information via the
NGSI-LD API. The consequences of this may be severe in the case of modification or deletion requests
for legal reasons, e.g. GDPR [i.18]. When implementing the NGSI-LD API on storage systems that do
NOT allow modification or deletion, similar problems may be encountered.

**Describe the solution you'd like**
1. When a new entity is received, automatically and id is generated from the backend db.

**Describe alternatives you've considered**

Well doing nothing about it :)

**Additional context**
N/A

**Comment by pooja1pathak** [comment]
@chicco785 I would like to contribute on this issue. For that I need little clarification on:
> 1. When a new entity is received, automatically and id is generated from the backend db.

We need to create a new column named ```instanceId```, and whenever we receive an update for entity we should add unique value to ```instanceId```. So each row inside the table is uniquely identified by ```instanceId```

**Comment by pooja1pathak** [comment]
Closing as PR #565 is merged.
