### ISSUE TITLE
arbitrary type arrays cause errors when inserting to Timescale

### ISSUE THREAD

**Issue by ilarimikkonen** [orchestracities/ngsi-timeseries-api#537]
**Describe the bug**
Sending a data (interesting part is the valueArray) like this: 
```
{
	"id": "six",
	"testcase": {
		"type": "Text",
		"value": "type as Moosbllord, value name doesthismatter2 and random values in an array"
	},
	"doesthismatter2": {
            "type": "Moosbllord",
            "value": ["oglera8978sdfasd", "fdasfa6786sdf"]
    }

}
```

via Orion context broker causes this error in QL:

```
{
    "data": {
        "id": "six",
        "type": "Thing",
        "time_index": "2021-08-30T07:38:58.995464",
        "serialNumber": {
            "type": "Text",
            "value": "type as Moosbllord, new value name doesthismatter2 and random values in an array",
            "metadata": {}
        },
        "doesthismatter2": {
            "type": "Moosbllord",
            "value": [
                "oglera8978sdfasd",
                "fdasfa6786sdf"
            ],
            "metadata": {}
        }
    },
    "error": "ProgrammingError({'S': 'ERROR', 'V': 'ERROR', 'C': '42804', 'M': 'column \"doesthismatter2\" is of type jsonb but expression is of type text[]', 'H': 'You will need to rewrite or cast the expression.', 'P': '179', 'F': 'parse_target.c', 'L': '591', 'R': 'transformAssignedExpr'})",
    "failedBatchID": "d0252067802e432aa3675044cd6fa4fb"
}
```

**To Reproduce**
send the data shown above and observe the error. Error in question is copied from Timescale UI.

**Expected behavior**
Data would be stored in Timescale as Text array ot JSON blob

**Environment (please complete the following information):**
ql version 0.8.2

**Additional context**
section [ATTRIBUTES DATATYPE TRANSLATION](https://quantumleap.readthedocs.io/en/latest/user/using/) describes how the translations are done, I believe it may need a new case to be checked.

**Comment by chicco785** [comment]
the problem could be due to the `type` and automatic detection, text arrays are covered in tests:

https://github.com/orchestracities/ngsi-timeseries-api/blob/master/src/reporter/tests/test_notify.py#L588

**Comment by ilarimikkonen** [comment]
> If the first payload is for the creation of the entity you are missing the entity type which is mandatory.
> You should include something like
> "type": "MyEntityType"

if the type is omitted, then it defaults to "type": "Thing",

**Comment by chicco785** [comment]
@ilarimikkonen @albertoabellagarcia as you can see from the pr #540 the bug is confirmed, we will review and merge the pr in the next days.

**Comment by albertoabellagarcia** [comment]
What I can tell you is that if you change the type Moosbllord by type Text it works.

**Comment by chicco785** [comment]
@ilarimikkonen the pr was merged, a new image (tag as per new policy of images for master is `edge` ,`latest` from 0.8.3 will map only to the latest official release)

**Comment by albertoabellagarcia** [comment]
So, what's the status of the issue. Should it be closed?

**Comment by ilarimikkonen** [comment]
for me closed is ok.

**Comment by chicco785** [comment]
@ilarimikkonen if you tested the "edge" image and you confirm the resolution, fill free to close the issue (as its creator). if not, we will close it when it became "stale". thx!

**Comment by jplindblom** [comment]
Tested with edge, fix works.
