### ISSUE TITLE
https://app.swaggerhub.com/apis/smartsdk/ngsi-tsdb/0.8.2 page does not exists

### ISSUE THREAD

**Issue by ilarimikkonen** [orchestracities/ngsi-timeseries-api#538]
**Describe the bug**
the latest version of the API description is not available.

**To Reproduce**
1. visit page: https://app.swaggerhub.com/apis/smartsdk/ngsi-tsdb/0.8.2

**Expected behavior**
page exists and documentation is rendered and correct per new version

**Environment (please complete the following information):**
N/A

**Comment by chicco785** [comment]
fixed
