### ISSUE TITLE
If possible reference proper document about `options=sysAttrs`.

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#546]
This is `options=sysAttrs` - the `modifiedAt` is generated by the Context Broker for each attribute and for the entity as a whole. I think there could be a divergence if an entity has multiple attributes and only some are updated since the unmodified attributes would have an older `modifiedAt` timestamp.

Obviously this won't be an issue for a subscribing component since the notification will only be raised when an attribute changes.

_Originally posted by @jason-fox in https://github.com/orchestracities/ngsi-timeseries-api/pull/496#discussion_r699073795_

**Comment by jason-fox** [comment]
From the NGSI-LD [ETSI Specification](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.04.01_60/gs_cim009v010401p.pdf)

>  ### 6.3.11 Including system-generated attributes
>
> For HTTP GET operations performed over the resources `/entities/`, `/subscriptions/`, `/csourceRegistrations/`,
> `/csourceSubscriptions/` and all of its sub-resources, implementations shall support the parameter specified in
> the table below
>
> -   `options` - a comma separated list of strings. When its value includes the keyword `sysAttrs`, a
> representation of NGSI-LD Elements shall be provided so that the system-generated attributes `createdAt`, 
> `modifiedAt` are included in the response payload body.

**Comment by chicco785** [comment]
> From the NGSI-LD [ETSI Specification](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.04.01_60/gs_cim009v010401p.pdf)
> 
> > ### 6.3.11 Including system-generated attributes
> > For HTTP GET operations performed over the resources `/entities/`, `/subscriptions/`, `/csourceRegistrations/`,
> > `/csourceSubscriptions/` and all of its sub-resources, implementations shall support the parameter specified in
> > the table below
> > 
> > * `options` - a comma separated list of strings. When its value includes the keyword `sysAttrs`, a
> >   representation of NGSI-LD Elements shall be provided so that the system-generated attributes `createdAt`,
> >   `modifiedAt` are included in the response payload body.

thanks!
