### ISSUE TITLE
update cache backend section with info on geocoding cache and wq cache

### ISSUE THREAD

**Issue by chicco785** [orchestracities/ngsi-timeseries-api#559]
**Is your feature request related to a problem? Please describe.**

Caching doc does not cover geoqueries and wq:
https://github.com/orchestracities/ngsi-timeseries-api/blame/master/docs/manuals/index.md#L239

**Describe the solution you'd like**
More complete doc

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by daminichopra** [comment]
Hi  @c0c0n3 @chicco785 , I would like to contribute in this issue. Please assign 
Thank you!!
