### ISSUE TITLE
Deprecate smartsdk image

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/ngsi-timeseries-api#571]
### Describe the issue
When moving the QL repo from smartsdk to orchestra, we missed the old smartsdk Docker image. At the moment, this is causing confusion among our users. For example, here's a report from the trenches by @jason-fox

> ...the issue was that the user was using an out-of-date image and didn't know where the newer ones were.

In fact, the old smartsdk image is still there on DockerHub

- https://hub.docker.com/r/smartsdk/quantumleap 

without any indication that you should actually use

- https://hub.docker.com/r/orchestracities/quantumleap

### Proposed solution
Just copy-pasting @jason-fox's suggestion as I think it's a very good solution:

"Just add something like

> The SmartSDK docker images are no longer actively maintained, newer releases can be found under OrchestraCities [link]

To the head of the README. To be honest, you could remove all the current badges and what-have-you from the README as well - the problem is that because it is well written, the old README doesn't look neglected enough. :-)

You could also  add the deprecated badge if you wish:

![](https://nexus.lab.fiware.org/static/badges/statuses/deprecated.svg)
 I have an example here: https://github.com/FIWARE/data-models/blob/master/README.md
"

**Comment by pooja1pathak** [comment]
Hi @c0c0n3 I looked into this issue, the Readme of dockerhub page is same as that of github's page. Also the link for repository is pointing to the newer one i.e., orchestracities. 

I have not found any way to edit this page. Please let me know if we can edit dockerhub page by github or need manually edit the page on dockerhub (I don't have access to edit the page manually).

**Comment by jason-fox** [comment]
You'll need to have edit access and amend the page manually. The obsolete image isn't building from GitHub any more.

**Comment by chicco785** [comment]
docker hub page modified manually.
