### ISSUE TITLE
Update Deprecated warning from "warn" to "warning" 

### ISSUE THREAD

**Issue by daminichopra** [orchestracities/ngsi-timeseries-api#606]
**Describe the bug**
While running test cases there is deprecation warning for `warn`
Updated some left out files with `warning`

**To Reproduce**
NA

**Expected behavior**
NA
**Environment (please complete the following information):**
 - OS: [LINUX]
 - Browser [chrome]

**Additional context**

**Comment by daminichopra** [comment]
Updated in [PR](https://github.com/orchestracities/ngsi-timeseries-api/pull/605)

**Comment by pooja1pathak** [comment]
closing as PR #605 is merged
