### ISSUE TITLE
Envs for CrateDB Authentication have wrong Names in Documentation

### ISSUE THREAD

**Issue by StWiemann** [orchestracities/ngsi-timeseries-api#636]
The names of the envs for CrateDB-authentication are wrong in the [documentation](https://quantumleap.readthedocs.io/en/latest/admin/configuration/).
Debug-logs revealed that QL is expecting:

CRATE_DB_USER instead of CRATE_DB_USERNAME
and
CRATE_DB_PASS instead of CRATE_DB_PASSWORD

**Comment by chicco785** [comment]
@StWiemann thanks, I think this is a refuse from initial PR that introduced cratedb authentication. We will fix this shortly.
