### ISSUE TITLE
Remove duplicate code

### ISSUE THREAD

**Issue by pooja1pathak** [orchestracities/ngsi-timeseries-api#655]
Remove duplicate code mentioned at:

https://github.com/orchestracities/ngsi-timeseries-api/blob/81351ec96f87175de253dbfc26c8dfbdf3062cd3/src/reporter/tests/test_timescale_types.py#L31

**Comment by NEC-Vishal** [comment]
Hi @chicco785 @c0c0n3 
can you please clarify this TODO that which part of code is duplicate in test_timescale_type.py 
or if code is not duplicate in this file then which translator file contains this code?

**Comment by NEC-Vishal** [comment]
Hi @chicco785 @c0c0n3 
as per my analysis, I found that gen_tenant_id() is common function used in some files of translator and reporter section.
![image](https://user-images.githubusercontent.com/105697861/172810413-31282ace-b375-4bd0-a1bc-f84fd834ced5.png)

so I am thinking of making a separate file named tenant.py in src/utils and then import that file to all files that contain the duplicate function.
this will remove the duplicity in files.

Please guide me!

**Comment by c0c0n3** [comment]
@NEC-Vishal that's great, thanks a stack. if you could please put the new file in the tests dir, i.e. `src/utils/tests/tenant.py`.

**Comment by NEC-Vishal** [comment]
> @NEC-Vishal that's great, thanks a stack. if you could please put the new file in the tests dir, i.e. `src/utils/tests/tenant.py`.

Hi @c0c0n3 
modifications are completed, please check!

**Comment by c0c0n3** [comment]
Hi @NEC-Vishal, see my comments to #657

**Comment by pooja1pathak** [comment]
Closing as PR #657 is merged.
