### ISSUE TITLE
Todo logging in src/wq/core/task.py

### ISSUE THREAD

**Issue by pooja1pathak** [orchestracities/ngsi-timeseries-api#662]
Add log as mentioned in:
https://github.com/orchestracities/ngsi-timeseries-api/blob/46a4fd4db18c0e7a337e843f89ba350609e1d5ef/src/wq/core/task.py#L273
and https://github.com/orchestracities/ngsi-timeseries-api/blob/46a4fd4db18c0e7a337e843f89ba350609e1d5ef/src/wq/core/task.py#L275

**Comment by c0c0n3** [comment]
implemented by #663
