### ISSUE TITLE
Establish compatibility with Orion-LD.

### ISSUE THREAD

**Issue by DasNordlicht** [orchestracities/ngsi-timeseries-api#664]
NGSI-LD uses a new header NGSI-Teanant instead of Fiware-Service in the notifications.
Is it possible to use this header to realize the division in TSDB schemas?

`{
	"host": "xxxxx",
	"user-agent": "orion/1.15.0-next libcurl/7.61.1",
	"ngsild-tenant": "captn",
	"fiware-servicepath": "/",
	"accept": "application/json",
	"content-length": "1051",
	"content-type": "application/json; charset=utf-8",
	"ngsiv2-attrsformat": "normalized",
	"link": "<https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.5.jsonld>; rel=\"http://www.w3.org/ns/json-ld#context\"; type=\"application/ld+json\""
}`

**Comment by c0c0n3** [comment]
@DasNordlicht thank you so much for raising this. The latest [NGSI-LD spec][spec] is actually quite clear about it---4.14, 6.3.14. We'll look into this, but for the time being, can you try using the old `fiware-service` header? That should work, provided context broker sends it on to quantum leap---which it should I think...

[spec]: https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.05.01_60/gs_CIM009v010501p.pdf

**Comment by c0c0n3** [comment]
hi @DasNordlicht 

> NGSI-LD uses a new header NGSI-Teanant instead of Fiware-Service in the notifications.

As of #721, QuantumLeap supports the NGSI tenant header.

> Is it possible to use this header to realize the division in TSDB schemas?

Yes, the NGSI tenant header works in QL just like the FIWARE service header. In particular, if you send data with, say, an HTTP header of `ngsild-tenant: captn`, then QL will create a schema named `mtcaptn` where it will store all the entities for tenant `captn`.

**Comment by c0c0n3** [comment]
For the record, kudos to @rohit-vrrr who implemented the feature!
