### ISSUE TITLE
Linter failures in PR

### ISSUE THREAD

**Issue by pooja1pathak** [orchestracities/ngsi-timeseries-api#670]
**Describe the bug**
As per my observation, after merging of PR #653 , linter is failing.
There is some fixing required to correct this.

**To Reproduce**
1. Raise PR

**Expected behavior**
Linter should pass

**Environment (please complete the following information):**
NA

**Additional context**
NA

**Comment by Necravisaketi** [comment]
#671

**Comment by c0c0n3** [comment]
closed by #671
