### ISSUE TITLE
Fix TODO in Dockerfile

### ISSUE THREAD

**Issue by pooja1pathak** [orchestracities/ngsi-timeseries-api#680]
Fix TODO in Dockerfile:
https://github.com/orchestracities/ngsi-timeseries-api/blob/296db858f206b18491b61781e8d9562ed4b04942/timescale-container/Dockerfile#L11

**Comment by c0c0n3** [comment]
@pooja1pathak this TODO is outdated I think, in the end it looks like we decided to use env vars---see the code below the TODO. So I think all we need to do here is delete the TODO line :-)

**Comment by NEC-Vishal** [comment]
Hi @c0c0n3 
Thanks much for guiding us, Let me raise a pull request for deleting the TODO line.

**Comment by c0c0n3** [comment]
closed by #681
