### ISSUE TITLE
Resolve TODO in crate-exporter.py

### ISSUE THREAD

**Issue by pooja1pathak** [orchestracities/ngsi-timeseries-api#702]
Resolve TODO at:
https://github.com/orchestracities/ngsi-timeseries-api/blob/af8877cd2b5909c67819d8a93e3b58bce6a61fdb/timescale-container/crate-exporter.py#L76

**Comment by pooja1pathak** [comment]
@c0c0n3 I have gone through your comment on #704. 
Can we go with the implementation as in https://github.com/orchestracities/ngsi-timeseries-api/blob/270a4e266f2747b351ab6754d96bad205c0923a8/timescale-container/quantumleap-db-setup.py#L173 for escaping? Please let me know your opinion on this so I can raise a fresh PR.

**Comment by c0c0n3** [comment]
@pooja1pathak yes, good idea! I'd drop #704 and start from scratch w/ the approach you suggested.
