### ISSUE TITLE
Read the Docs deprecation

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/ngsi-timeseries-api#731]
**Is your feature request related to a problem? Please describe.**
Read the Docs are upgrading their builder. This could break our doc gen pipeline and produce garbage in the online docs.

**Describe the solution you'd like**
Either upgrade to the latest Read the Docs or pin the version. Ideally we should upgrade, well as long as it doesn't turn out to be a massive amount of work, in which case we could just pin the MkDocs version for now.

**Describe alternatives you've considered**
N/A

**Additional context**
See email below from Read the Docs.

**Comment by c0c0n3** [comment]
Here's the email notification we got from Read the Docs.

### [Action required] Make sure your project is compatible with MkDocs >= 1.x

Hello,

You are receving this email because your Read the Docs project is impacted by an upcoming deprecation.

Historically, Read the Docs has installed MkDocs `0.17.3` by default if the project didn't define a specific version of it. Now, this version is a pretty old and we recommend our users to use the latest version of MkDocs: `1.5.1`.

To avoid failing builds we kept the old default version of MkDocs. We are changing that behavior to always install the latest available version and we wanted to let you know about that so you can prepare your project.

**Starting on October 3rd Read the Docs will install the latest available version of MkDocs**. If you want to use a different version, make sure you are pinning your MkDocs dependency.

Here you have a pretty simple example of the section required on the `.readthedocs.yaml` configuration file:

```yaml
python:
  install:
    - requirements: docs/requirements.txt
```

The content of `docs/requirements.txt` would be similar to:

```
mkdocs==1.5.1
```

We are sending you this email because you are a maintainer of the following projects that are affected by this removal:

- [quantumleap](https://readthedocs.org/projects/quantumleap/)

Read more about this in our [Reproducible builds](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html) guide for more details.

Keep documenting,

Read the Docs

**Comment by c0c0n3** [comment]
@pooja1pathak's #771 updated the MkDocs build. Let's check it works on ReadTheDocs too before closing this issue.

**Comment by pooja1pathak** [comment]
@c0c0n3 As per my knowledge we need to execute `Rebuild version` on ReadTheDocs to check if this change work.

**Comment by c0c0n3** [comment]
@pooja1pathak I've just triggered a fresh build on ReadTheDocs and it worked like a charm, thanks so much!
