### ISSUE TITLE
orionld fiware-servicepath is not segregating data

### ISSUE THREAD

**Issue by tonyrosset** [orchestracities/ngsi-timeseries-api#756]
orion:
    labels:
      org.fiware: 'twinair'
    image:  fiware/orion-ld:1.5.0
    restart: unless-stopped
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    ports:
      - "${EXPOSED_PORT}:${ORION_LD_PORT}" # localhost:1026
    environment:
      - ORIONLD_MULTI_SERVICE=TRUE
    command: -dbhost mongo-db -logLevel DEBUG -forwarding -t 0-255
    healthcheck:
      test: curl --fail -s http://orion:${ORION_LD_PORT}/version || exit 1
      interval: 5s

even after opening the multi service, the data are not stored in specified servicepath instead at the default path "/"
![Screenshot 2024-05-06 130530](https://github.com/orchestracities/ngsi-timeseries-api/assets/106377529/2a1df76b-7997-4f76-a3a6-f8ee0de54d13)

**Comment by c0c0n3** [comment]
@tonyrosset I think this is a problem w/ Orion rather than Quantum Leap? I'm closing this issue, please reopen if my reading of your problem description is wrong :-)
