### ISSUE TITLE
DEFAULT_LIMIT  is not working

### ISSUE THREAD

**Issue by tonyrosset** [orchestracities/ngsi-timeseries-api#763]
DEFAULT_LIMIT  when set to a value more than 10000, it has noeffect it directs back to 10000

 environment:
      - CRATE_HOST=crate
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - LOGLEVEL=ERROR
      - DEFAULT_LIMIT=1000000

**Comment by c0c0n3** [comment]
@tonyrosset thanks for reporting this, we'll look into it...

**Comment by c0c0n3** [comment]
@tonyrosset are you using the `limit` and `last_n` params in the API call? If not, it could be there's a problem with CrateDB. I'm just looking at the code that figures out what the SQL limit actual value should be:

- https://github.com/orchestracities/ngsi-timeseries-api/blob/668490c0643fb2f46b6c6678fbaa36856f067d01/src/translators/sql_translator.py#L781

What's the API call you make to retrieve results?

**Comment by tonyrosset** [comment]
thanks,
I am not using the limit or lastN.  By default, when I set no DEFAULT_LIMIT I get 10,000 rows in the API call. When I set it to 100, I get 100 rows as supposed to be. The problem is only when I try to set the limit more than 10,000.

http://localhost:8668/v2/types/hwsensors?attrs=airTemperature&fromDate=2024-05-01T13:00:00&toDate=2024-06-12T09:00:00

**Comment by c0c0n3** [comment]
@tonyrosset, @pooja1pathak has just landed #765 which should fix the issue.

**Comment by tonyrosset** [comment]
@pooja1pathak thanks, 
@c0c0n3 Once u have accepted the commit at your repo I can use it, right?

**Comment by c0c0n3** [comment]
> Once u have accepted the commit at your repo I can use it

if you only need to link the code, then the fix will be available as soon as I merge #765 into the main branch. But I guess you'd like to download a Docker image with the fix? We have a GitHub action to automatically build and push Docker images to DockerHub when a PR gets merged into main:
- https://github.com/orchestracities/ngsi-timeseries-api/blob/master/.github/workflows/docker.yml

but unfortunately it's broken at the moment---I think it's just a silly thing w/ credentials having expired. Anyhoo, you can still build your own Docker image using the Docker file in the repo's root dir:
- https://github.com/orchestracities/ngsi-timeseries-api/blob/master/Dockerfile

there's also a build script:
- https://github.com/orchestracities/ngsi-timeseries-api/blob/master/build.sh

Hope that helps!

**Comment by tonyrosset** [comment]
thanks, that helps,
also, it would be great if you tell me when the docker image is updated.
Thanks once again.

**Comment by c0c0n3** [comment]
@tonyrosset #765 should've fixed the problem. So I'm closing this GitHub issue, but please feel free to reopen if the fix doesn't work for you.

**Comment by c0c0n3** [comment]
@tonyrosset sorry I've done this too quickly. We haven't merged #765 into main yet, so there's no easy way for you to test just yet. I'll close this issue when @pooja1pathak is done w/ #765 and we finally merge it. Sorry for the confusion!

**Comment by tonyrosset** [comment]
It is okay. we can wait

**Comment by tonyrosset** [comment]
Hi all, I'm not sure if you have merged it. Do let me know the status ) @c0c0n3 @pooja1pathak

**Comment by pooja1pathak** [comment]
@tonyrosset some tests are failing for the fix. I am working on it and will update once it gets fixed.

**Comment by tonyrosset** [comment]
> [@tonyrosset](https://github.com/tonyrosset) some tests are failing for the fix. I am working on it and will update once it gets fixed.

@pooja1pathak, any updates on the fixes?
