### ISSUE TITLE
Postgres Version Suppert

### ISSUE THREAD

**Issue by lucboj** [orchestracities/ngsi-timeseries-api#767]
Hello, 

when I look around in the repository I see that Postgres 13 is mentioned. Should this be seen as the latest version from Postgres which can be used with QuantumLeap or has QuantumLeap been tested with other versions?

**Comment by c0c0n3** [comment]
Hello @lucboj :-)

> has QuantumLeap been tested with other versions?

Short answer: No we haven't. But some of our users might have. 

The latest version of the Postgres/Timescale/Postgis stack we have tested with is Postgres `13` with Timescale `2.3.0` and Postgis `2.5` extensions. I think Postres `16` is mostly compatible w/ `13` and a more recent version of Timescale should work too, but like I said we never actually tried.
